#!/usr/bin/env bash

clear

set -eo pipefail

if [ ! -f "index.php" ]; then
  echo 'Please run this script from "drupal8" directory.'
  exit 1;
fi

$(echo $(pwd)"/scripts/project-branch");

echo "PHP Logs ..."

docker logs -f starter_php_1
